version: '3.9'

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rdebug-ide --host 0.0.0.0 --port 1234 -- bin/rails s -p 3000 -b 0.0.0.0"
    ports:
      - '3000:3000'
      - '1234:1234'
    depends_on:
      - db
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    environment:
      - DBUSERNAME=root
      - DBPASSWORD=/run/secrets/db_password
      - WEB_CONCURRENCY=0
      - RAILS_MAX_THREADS=1
    secrets:
      - db_password
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=/run/secrets/db_password
    secrets:
      - db_password

volumes:
  node_modules:
  db:

secrets:
  db_password:
      file: db_password.txt # add this file to gitignore